from __future__ import annotations
from ..models.circuit import SimulationRequest, ComponentType


SPICE_PREFIX: dict[ComponentType, str] = {
    ComponentType.resistor: "R",
    ComponentType.capacitor: "C",
    ComponentType.inductor: "L",
    ComponentType.voltageSource: "V",
    ComponentType.currentSource: "I",
    ComponentType.switch: "S",
    ComponentType.led: "D",
}


def sanitize_id(cid: str) -> str:
    return "".join(c for c in cid if c.isalnum() or c == "_") or "X"


def build_netlist(req: SimulationRequest) -> str:
    lines = ["* Circuit Lab — SPICE Netlist", "* Generated by simulation engine", ""]

    # Resolve merged node IDs through wires
    node_map: dict[int, int] = {}
    for t in req.terminals.values():
        node_map[t.nodeId] = t.nodeId

    for w in req.wires:
        ft = req.terminals.get(w.fromTerminalId)
        tt = req.terminals.get(w.toTerminalId)
        if ft is None or tt is None:
            continue
        a, b = ft.nodeId, tt.nodeId
        if a == b:
            continue
        old = max(a, b)
        new = min(a, b)
        for k in list(node_map.keys()):
            if node_map[k] == old:
                node_map[k] = new

    def resolve(n: int) -> int:
        while node_map[n] != n:
            node_map[n] = node_map[node_map[n]]
            n = node_map[n]
        return n

    for k in node_map:
        node_map[k] = resolve(k)

    # Build terminal index per component
    comp_terms: dict[str, dict[int, int]] = {}
    for cid in req.components:
        comp_terms[cid] = {}
    for t in req.terminals.values():
        if t.componentId in comp_terms:
            comp_terms[t.componentId][t.index] = resolve(t.nodeId)

    model_defs: list[str] = []

    for cid, comp in req.components.items():
        terms = comp_terms.get(cid)
        if terms is None or 0 not in terms or 1 not in terms:
            continue
        n0 = terms[0]
        n1 = terms[1]
        ref = f"{n0} {n1}"
        pref = SPICE_PREFIX.get(comp.type, "R")
        sid = sanitize_id(cid)

        if comp.type == ComponentType.resistor:
            r = comp.params.get("resistance", 1000)
            if r <= 0:
                r = 1e-9
            lines.append(f"{pref}{sid} {ref} {r}")

        elif comp.type == ComponentType.capacitor:
            cv = comp.params.get("capacitance", 1e-6)
            if cv <= 0:
                cv = 1e-12
            lines.append(f"{pref}{sid} {ref} {cv} IC=0")

        elif comp.type == ComponentType.inductor:
            lv = comp.params.get("inductance", 1e-3)
            if lv <= 0:
                lv = 1e-12
            lines.append(f"{pref}{sid} {ref} {lv} IC=0")

        elif comp.type == ComponentType.voltageSource:
            v = comp.params.get("voltage", 9)
            lines.append(f"V{sid} {n0} 0 DC {v}")
            lines.append(f"R_VSENSE_{sid} {n1} 0 1e-6")

        elif comp.type == ComponentType.currentSource:
            i = comp.params.get("current", 0.01)
            lines.append(f"I{sid} {ref} DC {i}")

        elif comp.type == ComponentType.led:
            fv = comp.params.get("forwardVoltage", 2.0)
            model_name = f"DLED_{sid}"
            lines.append(f"D{sid} {ref} {model_name}")
            model_defs.append(f".MODEL {model_name} D(IS=1e-14 N=1.5 VJ={fv})")

        elif comp.type == ComponentType.switch:
            closed = comp.params.get("isClosed", 0)
            if closed:
                lines.append(f"R_SW_{sid} {ref} 0.001")
            else:
                lines.append(f"R_SW_{sid} {ref} 1e9")

        elif comp.type == ComponentType.ground:
            lines.append(f"R_GND_{sid} {n0} 0 1e6")

    lines.append("")
    for m in model_defs:
        lines.append(m)

    lines.append("")
    if req.analysis == "dc":
        lines.append(".DC V0 0 0 1")
    else:
        lines.append(f".TRAN {req.timestep} {req.duration} UIC")
    lines.append(".OPTIONS POST=2")
    lines.append(".END")
    return "\n".join(lines)
